export const DEFAULT_SYMBOLS = ["AAPL", "MSFT", "NVDA", "AMZN", "TSLA", "SPY"];

export const WHEEL_UNIVERSE = [
  "AAPL",
  "ABBV",
  "ABNB",
  "AMD",
  "AMZN",
  "BAC",
  "BABA",
  "CCJ",
  "COIN",
  "COST",
  "CRM",
  "DIS",
  "ET",
  "F",
  "GOOGL",
  "HOOD",
  "INTC",
  "IWM",
  "JPM",
  "KO",
  "META",
  "MRVL",
  "MSFT",
  "NET",
  "NFLX",
  "NKE",
  "NVDA",
  "PLTR",
  "QQQ",
  "SCHW",
  "SHOP",
  "SMCI",
  "SOFI",
  "SPY",
  "TSLA",
  "UBER",
  "WMT",
  "XLF",
  "XOM",
];

export const TOOL_CARDS = [
  {
    title: "Premium Yield",
    description: "Measure raw yield on collateral for a wheel trade.",
    formula: "premium / strike x 100",
  },
  {
    title: "Annualized Yield",
    description: "Normalize shorter expirations against a yearly rate.",
    formula: "premium yield x (365 / DTE)",
  },
  {
    title: "Cash Required",
    description: "Reserve the buying power needed for a CSP assignment.",
    formula: "strike x 100 x contracts",
  },
  {
    title: "Breakeven",
    description: "See the effective stock basis after premium.",
    formula: "put strike - premium or stock cost - premium",
  },
];
